/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.CantonUI;
import GUI.*;

import static aplicacion.Aplicacion.controladorPrincipal;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Manuel Arias & Justin Bogantes
 */
public class Guanacaste extends javax.swing.JFrame {

    /**
     * Creates new form Guanacaste
     */
    public Guanacaste() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cantonLaCruz = new javax.swing.JButton();
        cantonLiberia = new javax.swing.JButton();
        cantonCarrillo = new javax.swing.JButton();
        cantonSantaCruz = new javax.swing.JButton();
        cantonNicoya = new javax.swing.JButton();
        cantonHojancha = new javax.swing.JButton();
        cantonNandayure = new javax.swing.JButton();
        cantonAbangares = new javax.swing.JButton();
        cantonBagaces = new javax.swing.JButton();
        cantonCañas = new javax.swing.JButton();
        cantonTilaran = new javax.swing.JButton();
        fondoGuanacaste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cantonLaCruz.setText("510");
        cantonLaCruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonLaCruzActionPerformed(evt);
            }
        });
        jPanel1.add(cantonLaCruz, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        cantonLiberia.setText("501");
        cantonLiberia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonLiberiaActionPerformed(evt);
            }
        });
        jPanel1.add(cantonLiberia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        cantonCarrillo.setText("505");
        cantonCarrillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonCarrilloActionPerformed(evt);
            }
        });
        jPanel1.add(cantonCarrillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        cantonSantaCruz.setText("503");
        cantonSantaCruz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonSantaCruzActionPerformed(evt);
            }
        });
        jPanel1.add(cantonSantaCruz, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        cantonNicoya.setText("502");
        cantonNicoya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonNicoyaActionPerformed(evt);
            }
        });
        jPanel1.add(cantonNicoya, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        cantonHojancha.setText("511");
        cantonHojancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonHojanchaActionPerformed(evt);
            }
        });
        jPanel1.add(cantonHojancha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 60, -1));

        cantonNandayure.setText("509");
        cantonNandayure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonNandayureActionPerformed(evt);
            }
        });
        jPanel1.add(cantonNandayure, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 710, -1, -1));

        cantonAbangares.setText("507");
        cantonAbangares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonAbangaresActionPerformed(evt);
            }
        });
        jPanel1.add(cantonAbangares, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        cantonBagaces.setText("504");
        cantonBagaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonBagacesActionPerformed(evt);
            }
        });
        jPanel1.add(cantonBagaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        cantonCañas.setText("506");
        cantonCañas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonCañasActionPerformed(evt);
            }
        });
        jPanel1.add(cantonCañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        cantonTilaran.setText("508");
        cantonTilaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantonTilaranActionPerformed(evt);
            }
        });
        jPanel1.add(cantonTilaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        fondoGuanacaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/mapa-CR-guanacaste.png"))); // NOI18N
        jPanel1.add(fondoGuanacaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantonLaCruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonLaCruzActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("La Cruz");
        ui.getLblCodigo().setText("510");
        ui.getLblPoblacion().setText("24.083" + " personas");
        ui.getLblAlfabetizacion().setText("94.0" + "%");
        ui.getLblConsumoElectrico().setText("399.2" + " kWh");
        ui.getLblMatriculaPrimaria().setText("86.2" + "%");
        ui.getLblMatriculaSecundaria().setText("79.9" + "%");
        ui.getLblMatriculaSuperior().setText("81.4" + "%");
        ui.getLblTerritorio().setText("1383.9" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/510.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonLaCruzActionPerformed

    private void cantonLiberiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonLiberiaActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Liberia");
        ui.getLblCodigo().setText("501");
        ui.getLblPoblacion().setText("68.785" + " personas");
        ui.getLblAlfabetizacion().setText("97,9" + "%");
        ui.getLblConsumoElectrico().setText("746,0" + " kWh");
        ui.getLblMatriculaPrimaria().setText("100.0" + "%");
        ui.getLblMatriculaSecundaria().setText("100.0" + "%");
        ui.getLblMatriculaSuperior().setText("100.0" + "%");
        ui.getLblTerritorio().setText("1436.5" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/501.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonLiberiaActionPerformed

    private void cantonCarrilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonCarrilloActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Carrillo");
        ui.getLblCodigo().setText("505");
        ui.getLblPoblacion().setText("40.558" + " personas");
        ui.getLblAlfabetizacion().setText("97.7" + "%");
        ui.getLblConsumoElectrico().setText("718.6" + " kWh");
        ui.getLblMatriculaPrimaria().setText("96.8" + "%");
        ui.getLblMatriculaSecundaria().setText("95.4" + "%");
        ui.getLblMatriculaSuperior().setText("95.8" + "%");
        ui.getLblTerritorio().setText("577.5" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/505.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonCarrilloActionPerformed

    private void cantonBagacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonBagacesActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Bagaces");
        ui.getLblCodigo().setText("504");
        ui.getLblPoblacion().setText("21.936" + " personas");
        ui.getLblAlfabetizacion().setText("96.1" + "%");
        ui.getLblConsumoElectrico().setText("647.2" + " kWh");
        ui.getLblMatriculaPrimaria().setText("91.6" + "%");
        ui.getLblMatriculaSecundaria().setText("94.6" + "%");
        ui.getLblMatriculaSuperior().setText("93.8" + "%");
        ui.getLblTerritorio().setText("1273,5" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/504.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonBagacesActionPerformed

    private void cantonCañasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonCañasActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Cañas");
        ui.getLblCodigo().setText("506");
        ui.getLblPoblacion().setText("30.415" + " personas");
        ui.getLblAlfabetizacion().setText("96.5" + "%");
        ui.getLblConsumoElectrico().setText("666.6" + " kWh");
        ui.getLblMatriculaPrimaria().setText("90.9" + "%");
        ui.getLblMatriculaSecundaria().setText("92.9" + "%");
        ui.getLblMatriculaSuperior().setText("92.4" + "%");
        ui.getLblTerritorio().setText("682.2" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/506.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonCañasActionPerformed

    private void cantonTilaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonTilaranActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Tilaran");
        ui.getLblCodigo().setText("508");
        ui.getLblPoblacion().setText("20.883" + " personas");
        ui.getLblAlfabetizacion().setText("96.4" + "%");
        ui.getLblConsumoElectrico().setText("727.3" + " kWh");
        ui.getLblMatriculaPrimaria().setText("100.0" + "%");
        ui.getLblMatriculaSecundaria().setText("100.0" + "%");
        ui.getLblMatriculaSuperior().setText("100.0" + "%");
        ui.getLblTerritorio().setText("638.4" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/508.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonTilaranActionPerformed

    private void cantonSantaCruzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonSantaCruzActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Santa Cruz");
        ui.getLblCodigo().setText("503");
        ui.getLblPoblacion().setText("61.706" + " personas");
        ui.getLblAlfabetizacion().setText("98.2" + "%");
        ui.getLblConsumoElectrico().setText("734.9" + " kWh");
        ui.getLblMatriculaPrimaria().setText("85.4" + "%");
        ui.getLblMatriculaSecundaria().setText("100.0" + "%");
        ui.getLblMatriculaSuperior().setText("96.3" + "%");
        ui.getLblTerritorio().setText("1312.3" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/503.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonSantaCruzActionPerformed

    private void cantonNicoyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonNicoyaActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Nicoya");
        ui.getLblCodigo().setText("502");
        ui.getLblPoblacion().setText("53.212" + " personas");
        ui.getLblAlfabetizacion().setText("97.2" + "%");
        ui.getLblConsumoElectrico().setText("712.5" + " kWh");
        ui.getLblMatriculaPrimaria().setText("100.0" + "%");
        ui.getLblMatriculaSecundaria().setText("100.0" + "%");
        ui.getLblMatriculaSuperior().setText("100.0" + "%");
        ui.getLblTerritorio().setText("1333.7" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/502.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonNicoyaActionPerformed

    private void cantonAbangaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonAbangaresActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Abangares");
        ui.getLblCodigo().setText("507");
        ui.getLblPoblacion().setText("19.081" + " personas");
        ui.getLblAlfabetizacion().setText("95.8" + "%");
        ui.getLblConsumoElectrico().setText("708.5" + " kWh");
        ui.getLblMatriculaPrimaria().setText("100.0" + "%");
        ui.getLblMatriculaSecundaria().setText("86.9" + "%");
        ui.getLblMatriculaSuperior().setText("90.2" + "%");
        ui.getLblTerritorio().setText("675.8" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/507.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonAbangaresActionPerformed

    private void cantonHojanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonHojanchaActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Hojancha");
        ui.getLblCodigo().setText("511");
        ui.getLblPoblacion().setText("7.685" + " personas");
        ui.getLblAlfabetizacion().setText("96.4" + "%");
        ui.getLblConsumoElectrico().setText("725.5" + " kWh");
        ui.getLblMatriculaPrimaria().setText("100.0" + "%");
        ui.getLblMatriculaSecundaria().setText("100.0" + "%");
        ui.getLblMatriculaSuperior().setText("100.0" + "%");
        ui.getLblTerritorio().setText("261.4" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/511.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonHojanchaActionPerformed

    private void cantonNandayureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantonNandayureActionPerformed
        CantonUI ui = new CantonUI();
        ui.getlblNombre().setText("Nandayure");
        ui.getLblCodigo().setText("509");
        ui.getLblPoblacion().setText("11.525" + " personas");
        ui.getLblAlfabetizacion().setText("96.4" + "%");
        ui.getLblConsumoElectrico().setText("563.5" + " kWh");
        ui.getLblMatriculaPrimaria().setText("100.0" + "%");
        ui.getLblMatriculaSecundaria().setText("100.0" + "%");
        ui.getLblMatriculaSuperior().setText("100.0" + "%");
        ui.getLblTerritorio().setText("565.6" + " km cuadrados");
        ui.setVisible(true);
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/Cantones/509.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(ui.getlblFoto().getWidth(), ui.getlblFoto().getHeight(), Image.SCALE_DEFAULT));
        ui.getlblFoto().setIcon(icono);
    }//GEN-LAST:event_cantonNandayureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guanacaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guanacaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guanacaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guanacaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guanacaste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cantonAbangares;
    private javax.swing.JButton cantonBagaces;
    private javax.swing.JButton cantonCarrillo;
    private javax.swing.JButton cantonCañas;
    private javax.swing.JButton cantonHojancha;
    private javax.swing.JButton cantonLaCruz;
    private javax.swing.JButton cantonLiberia;
    private javax.swing.JButton cantonNandayure;
    private javax.swing.JButton cantonNicoya;
    private javax.swing.JButton cantonSantaCruz;
    private javax.swing.JButton cantonTilaran;
    private javax.swing.JLabel fondoGuanacaste;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
